services:
  db:
    container_name: first-read-db
    build:
      context: .
      dockerfile: Dockerfile_PG
    ports:
      - $DATABASE_PORT:5432
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    volumes:
      - postgres-data:/var/lib/postgresql/data
 

volumes:
  postgres-data:

